### ISSUE TITLE
Error 21: Bad substitution when running run_bldg_agg.sh

### ISSUE THREAD

**Issue by artessen** [novelt/building-aggregation-tool#4]
Dear developers,

I have managed to install the container successfully after setting the variable `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True`, as without this the installation was not concluding due to the following error "The 'sklearn' PyPI package is deprecated, use 'scikit-learn'"

After installing the docker container, I can successfully launch the binbash.sh script and enter the docker container, however I do not have a folder named "build", and the script "run_bldg_agg.sh" is located in the home directory of the container.
I then proceed to run the following line as a test from within the container:
	`./run_bldg_agg.sh BLDG_AGG --country TGO`
But I still get the same error: `./run_bldg_agg.sh: 21: Bad substitution`

I have also tried the following command to check if it works, but the error persists:
	`./run_bldg_agg.sh BLDG_AGG --country NGA --gen-docs`
Error:
	`./run_bldg_agg.sh: 21: Bad substitution`

Would you have any suggestions on how to solve this issue?

Thank you very much,
Arthur

**Comment by eg-novelt** [comment]
Should be fixed in develop via https://github.com/novelt/building-aggregation-tool/commit/4643d59662d62a0cc404abe5c8f324253e13d34a
